FROM python:3.12.6-bullseye


WORKDIR /app

COPY requirements.txt /app/

COPY worker_init.sh /app/

RUN pip install -r requirements.txt

RUN apt-get -y update && apt-get install -y ffmpeg && apt-get clean




