FROM python:3.12.6-bullseye

RUN pip install poetry

WORKDIR /app

COPY requirements.txt /app/

RUN pip install -r requirements.txt

COPY server_init.sh /app
COPY api /app/api
COPY videocaption /app/videocaption
COPY build /app/build 
COPY manage.py /app
COPY media /app/media

EXPOSE 8000
